### PR TITLE
Alibouche

### PR DESCRIPTION
**Pull request by GhoudanAyoub**

### CODE REVIEW

**Comment by GhoudanAyoub** [comment]
@zakarmourad Check this one

**Comment by zakarmourad** [comment]
@GhoudanAyoub model.pitch use different class's khass yconn b7al model.user ,and why change port from 9090 to 1234.

**Comment by GhoudanAyoub** [comment]
@zakarmourad in pitch model  i think he added those annotations instead of creating multiple  method

**Comment by GhoudanAyoub** [comment]
@zakarmourad its  good for this  one im going to  merge it

**Pull request merged**
